# -*- coding: utf-8 -*-
"""Legal corpus audit & provenance registry.

Creates and refreshes a ``corpus_registry`` table that records, for every data
source in the system:

* how many records it actually contains (measured, not estimated),
* what its **provenance** is (authoritative / open-source / synthetic),
* whether it is **citable** to an end user as legal authority,
* and what licence governs commercial use.

Why this exists
---------------
A commercial legal AI lives or dies on citation integrity.  Mixing
template-generated synthetic records into the retrieval corpus is exactly how
products end up fabricating case numbers and getting sanctioned (700+ court
cases globally in 2026 involve AI-hallucinated citations).  The synthetic
corpus on disk (15M records) *must not* be presented as precedent.

This script makes that boundary explicit and machine-checkable, and gives a
defensible single source of truth for "how much legal data do we actually
have, and what may we legally use".

Usage (inside the backend container):

    python scripts/corpus_audit.py
    python scripts/corpus_audit.py --json out.json
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import time
from dataclasses import dataclass, asdict

import asyncpg

DEFAULT_DSN = os.environ.get(
    "DSN",
    "postgresql://postgres:postgres@postgres:5432/legal_assistant",
)

# Local synthetic corpus (generated by scripts/hundred_million_data_expansion.py)
MASS_EXPANSION_DIR = os.environ.get("MASS_EXPANSION_DIR", "/tmp/mass_expansion_files")


@dataclass
class CorpusSource:
    source_key: str
    display_name: str
    storage: str            # "postgres" | "milvus" | "local_file"
    location: str           # table / collection / path
    provenance: str         # "authoritative" | "open_source" | "synthetic"
    citable: bool           # may be shown to users as legal authority
    record_count: int
    commercial_use: str     # licence note
    note: str = ""


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS corpus_registry (
    source_key      varchar(96)  PRIMARY KEY,
    display_name    varchar(256) NOT NULL,
    storage         varchar(32)  NOT NULL,
    location        varchar(256) NOT NULL,
    provenance      varchar(32)  NOT NULL,
    citable         boolean      NOT NULL,
    record_count    bigint       NOT NULL DEFAULT 0,
    commercial_use  varchar(256),
    note            text,
    measured_at     timestamptz  NOT NULL DEFAULT now()
);
"""


async def table_count(conn: asyncpg.Connection, table: str) -> int:
    try:
        return await conn.fetchval(f"SELECT count(*) FROM {table}")  # noqa: S608
    except Exception:  # noqa: BLE001
        return -1


async def collect(conn: asyncpg.Connection) -> list[CorpusSource]:
    sources: list[CorpusSource] = []

    # ------------------------------------------------------------------
    # Authoritative / government-published sources -> citable
    # ------------------------------------------------------------------
    sources.append(CorpusSource(
        source_key="laws_npc",
        display_name="法律法规（国家法律法规数据库 全文）",
        storage="postgres",
        location="laws",
        provenance="authoritative",
        citable=True,
        record_count=await table_count(conn, "laws"),
        commercial_use="公开政府数据，可商用（需标注来源）",
        note="含国家法律法规数据库 + FLK 全量同步",
    ))
    sources.append(CorpusSource(
        source_key="legal_articles_fulltext",
        display_name="法条全文（按条切分）",
        storage="postgres",
        location="legal_articles",
        provenance="authoritative",
        citable=True,
        record_count=await table_count(conn, "legal_articles"),
        commercial_use="公开政府数据，可商用（需标注来源）",
        note="法条级检索主库，RAG 首选证据源",
    ))
    sources.append(CorpusSource(
        source_key="regulation_changes",
        display_name="法规动态变更",
        storage="postgres",
        location="regulation_changes",
        provenance="authoritative",
        citable=True,
        record_count=await table_count(conn, "regulation_changes"),
        commercial_use="公开数据，可商用",
        note="合规风险模块的法规跟踪依据",
    ))

    # ------------------------------------------------------------------
    # Open-source research datasets -> citable with caution
    # ------------------------------------------------------------------
    sources.append(CorpusSource(
        source_key="court_cases_opensource",
        display_name="裁判案例（开源数据集）",
        storage="postgres",
        location="court_cases",
        provenance="open_source",
        citable=True,
        record_count=await table_count(conn, "court_cases"),
        commercial_use="开源数据集，多为研究许可；商用前需逐源复核许可",
        note="⚠ 案例类数据商用许可需逐一核验，不可默认视为可商用",
    ))
    sources.append(CorpusSource(
        source_key="legal_qa_pairs",
        display_name="法律问答对",
        storage="postgres",
        location="legal_qa_pairs",
        provenance="open_source",
        citable=False,
        record_count=await table_count(conn, "legal_qa_pairs"),
        commercial_use="开源数据集，研究用途为主",
        note="用于检索增强/微调，不直接作为法律依据引用",
    ))
    sources.append(CorpusSource(
        source_key="legal_qa",
        display_name="法律咨询问答（SFT）",
        storage="postgres",
        location="legal_qa",
        provenance="open_source",
        citable=False,
        record_count=await table_count(conn, "legal_qa"),
        commercial_use="开源数据集，研究用途为主",
        note="中文法律 SFT 语料，可用于微调",
    ))
    sources.append(CorpusSource(
        source_key="legal_knowledge_entries",
        display_name="法律知识条目",
        storage="postgres",
        location="legal_knowledge_entries",
        provenance="open_source",
        citable=False,
        record_count=await table_count(conn, "legal_knowledge_entries"),
        commercial_use="开源数据集，研究用途为主",
        note="知识补全用",
    ))
    sources.append(CorpusSource(
        source_key="legal_cross_references",
        display_name="法条交叉引用",
        storage="postgres",
        location="legal_cross_references",
        provenance="open_source",
        citable=True,
        record_count=await table_count(conn, "legal_cross_references"),
        commercial_use="由公开法条派生，可商用",
        note="知识图谱关联边",
    ))
    sources.append(CorpusSource(
        source_key="legal_concepts",
        display_name="法律概念",
        storage="postgres",
        location="legal_concepts",
        provenance="open_source",
        citable=True,
        record_count=await table_count(conn, "legal_concepts"),
        commercial_use="自有整理，可商用",
        note="概念覆盖度不足，需扩充",
    ))

    # ------------------------------------------------------------------
    # Synthetic corpus -> NEVER citable
    # ------------------------------------------------------------------
    synthetic_qa = _count_lines(
        os.path.join(MASS_EXPANSION_DIR, "synthetic_qa_pairs.jsonl"),
        env_override="SYNTHETIC_QA_COUNT",
    )
    synthetic_cases = _count_lines(
        os.path.join(MASS_EXPANSION_DIR, "synthetic_cases.jsonl"),
        env_override="SYNTHETIC_CASES_COUNT",
    )
    sources.append(CorpusSource(
        source_key="synthetic_qa_pairs",
        display_name="合成问答（模板生成）",
        storage="local_file",
        location="mass_expansion/synthetic_qa_pairs.jsonl",
        provenance="synthetic",
        citable=False,
        record_count=synthetic_qa,
        commercial_use="自有生成物，可自由处置，仅限训练/压测",
        note="⛔ 严禁入库到检索语料或作为法律依据展示",
    ))
    sources.append(CorpusSource(
        source_key="synthetic_cases",
        display_name="合成案例（模板生成）",
        storage="local_file",
        location="mass_expansion/synthetic_cases.jsonl",
        provenance="synthetic",
        citable=False,
        record_count=synthetic_cases,
        commercial_use="自有生成物，可自由处置，仅限训练/压测",
        note="⛔ 案号与当事人均为虚构，展示即构成虚假引用风险",
    ))

    return sources


def _count_lines(path: str, env_override: str | None = None) -> int:
    """Count newline-delimited records.

    The synthetic corpus is ~16 GB and is deliberately *not* mounted into the
    application container, so callers can pass an ``env_override`` variable
    holding a count measured on the host instead.
    """
    if env_override:
        raw = os.environ.get(env_override, "").strip()
        if raw:
            try:
                return int(raw)
            except ValueError:
                pass
    if not os.path.exists(path):
        return -1
    n = 0
    with open(path, "rb") as f:
        for _ in f:
            n += 1
    return n


async def milvus_counts() -> dict[str, int]:
    try:
        from pymilvus import Collection, connections, utility
        connections.connect(host=os.environ.get("MILVUS_HOST", "milvus"),
                            port=os.environ.get("MILVUS_PORT", "19530"))
        out = {}
        for name in utility.list_collections():
            try:
                col = Collection(name)
                col.load()
                out[name] = col.num_entities
            except Exception:  # noqa: BLE001
                out[name] = -1
        return out
    except Exception:  # noqa: BLE001
        return {}


async def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dsn", default=DEFAULT_DSN)
    ap.add_argument("--json", dest="json_out", default=None)
    args = ap.parse_args()

    conn = await asyncpg.connect(args.dsn)
    try:
        await conn.execute(SCHEMA_SQL)
        sources = await collect(conn)

        # Vector store rows are recorded as their own storage entries.
        for name, cnt in (await milvus_counts()).items():
            if cnt <= 0:
                continue
            citable = name in ("legal_articles",)
            sources.append(CorpusSource(
                source_key=f"milvus_{name}",
                display_name=f"向量集合 {name}",
                storage="milvus",
                location=name,
                provenance="authoritative" if citable else "open_source",
                citable=citable,
                record_count=cnt,
                commercial_use="继承源数据集许可",
                note="用于语义检索；provenance 继承其来源表",
            ))

        # Persist
        await conn.execute("DELETE FROM corpus_registry")
        await conn.executemany(
            """
            INSERT INTO corpus_registry (source_key, display_name, storage, location,
                                         provenance, citable, record_count,
                                         commercial_use, note)
            VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
            """,
            [
                (s.source_key, s.display_name, s.storage, s.location, s.provenance,
                 s.citable, s.record_count, s.commercial_use, s.note)
                for s in sources
            ],
        )

        # ---------------- report ----------------
        citable = [s for s in sources if s.citable and s.record_count > 0]
        non_citable = [s for s in sources if not s.citable and s.record_count > 0]
        citable_total = sum(s.record_count for s in citable)
        synthetic_total = sum(s.record_count for s in sources if s.provenance == "synthetic" and s.record_count > 0)

        print("=" * 86)
        print("法律语料治理审计 (corpus provenance audit)")
        print("=" * 86)
        print(f"{'来源':40s} {'类型':14s} {'可引用':6s} {'记录数':>14s}")
        print("-" * 86)
        for s in sorted(sources, key=lambda x: -x.record_count):
            if s.record_count < 0:
                continue
            print(f"{s.display_name[:38]:40s} {s.provenance:14s} "
                  f"{'是' if s.citable else '否':6s} {s.record_count:>14,}")
        print("-" * 86)
        print(f"{'可引用（citation-grade）语料合计':40s} {'':14s} {'':6s} {citable_total:>14,}")
        print(f"{'不可引用语料合计':40s} {'':14s} {'':6s} {sum(s.record_count for s in non_citable):>14,}")
        print(f"{'其中合成数据（严禁展示）':40s} {'':14s} {'':6s} {max(synthetic_total,0):>14,}")
        print("=" * 86)
        print(f"目标 100,000,000 条可引用语料 → 当前完成度 "
              f"{citable_total / 100_000_000 * 100:.2f}%")

        if args.json_out:
            with open(args.json_out, "w", encoding="utf-8") as f:
                json.dump([asdict(s) for s in sources], f, ensure_ascii=False, indent=2)
            print(f"\nregistry written to {args.json_out}")

    finally:
        await conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
