"""Chat schemas -- request/response models for chat endpoints."""

import re
from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

# Pattern matching null bytes and ASCII control characters (except common whitespace)
_CONTROL_CHAR_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


class ChatFileAttachment(BaseModel):
    """A file attached to a chat message."""
    filename: str = Field(..., description="Original filename")
    file_id: str | None = Field(default=None, description="Server-side file ID after upload")
    content: str | None = Field(default=None, description="Extracted text content from the file")


class ChatRequest(BaseModel):
    """Request body for sending a chat message."""
    conversation_id: str | None = Field(
        default=None, description="Existing conversation ID; if omitted, a new conversation is created."
    )
    message: str = Field(default="", min_length=0, max_length=10000, description="User message content")
    agent_type: str = Field(
        default="legal_consultation",
        description="Agent type: legal_consultation, contract_review, document_generation",
    )
    stream: bool = Field(default=False, description="Whether to stream the response")
    auto_normalize: bool = Field(
        default=True,
        description="Auto-convert colloquial/dialect phrasing into professional legal language before routing.",
    )
    # ── Enhanced features ──
    enable_deep_think: bool = Field(
        default=False,
        description="Enable deep thinking / IRAC reasoning mode",
    )
    enable_web_search: bool = Field(
        default=False,
        description="Enable web search to supplement answer with real-time internet data",
    )
    enable_multi_agent: bool = Field(
        default=False,
        description="Enable multi-agent collaboration (P1.6): fan out to specialized legal agents and synthesize",
    )
    files: list[ChatFileAttachment] | None = Field(
        default=None,
        description="List of file attachments (PDF/DOCX/TXT/Markdown) with extracted text",
    )
    mcp_tools: list[str] | None = Field(
        default=None,
        description="List of MCP tool names to invoke during response generation",
    )
    skill_id: str | None = Field(
        default=None,
        description="ID of the legal skill pack to execute",
    )

    @field_validator("message")
    @classmethod
    def sanitize_message(cls, v: str) -> str:
        """Strip null bytes and control characters from user input."""
        return _CONTROL_CHAR_RE.sub("", v)


class ChatResponse(BaseModel):
    """Response returned after a chat message."""
    conversation_id: str
    message_id: str
    role: str = "assistant"
    content: str
    tokens_used: int | None = None
    metadata: dict[str, Any] | None = Field(default=None, description="Citations, sources, etc.")
    created_at: datetime
    content_filtered: bool = Field(default=False, description="Whether content safety filtering was applied")
    disclaimer: str = Field(
        default="重要提示：以下内容由 AI 生成，仅供学习参考，不构成正式法律建议。具体法律问题请咨询持证律师。",
        description="AI response disclaimer",
    )
    ai_generated: bool = Field(
        default=True,
        description="Whether the content was generated by AI (per 人工智能生成合成内容标识办法)",
    )
    watermark_info: dict[str, Any] | None = Field(
        default=None,
        description="AI content watermark metadata (model, timestamp, user_hash) per AI labeling regulations",
    )
    generation_metadata: dict[str, Any] | None = Field(
        default=None,
        description="Content generation metadata including model, timestamp, and provenance info",
    )


class VoiceChatResponse(ChatResponse):
    """Response for voice-input chat, extending ChatResponse with transcription metadata."""
    transcribed_text: str = Field(..., description="The speech-to-text transcription result")
    audio_duration: float = Field(default=0.0, description="Audio duration in seconds")


class MessageResponse(BaseModel):
    """A single message in a conversation history."""
    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    id: str
    conversation_id: str
    role: str
    content: str
    tokens_used: int | None = None
    metadata: Any | None = Field(default=None, alias="metadata_")
    created_at: datetime
    ai_generated: bool = Field(
        default=False,
        description="Whether this message content was AI-generated",
    )
    generation_metadata: dict[str, Any] | None = Field(
        default=None,
        description="AI content generation metadata per labeling regulations",
    )

    @classmethod
    def model_validate(cls, obj, **kwargs):
        """Override to handle metadata JSON string from DB."""
        if hasattr(obj, '__dict__'):
            # SQLAlchemy model - convert metadata_ from JSON string to dict
            data = {}
            for key in ['id', 'conversation_id', 'role', 'content', 'tokens_used', 'created_at']:
                data[key] = getattr(obj, key, None)
            # Handle metadata_ - it's stored as a JSON string in DB
            raw_meta = getattr(obj, 'metadata_', None)
            parsed_meta = None
            if isinstance(raw_meta, str):
                import json as _json
                try:
                    parsed_meta = _json.loads(raw_meta)
                except (ValueError, TypeError):
                    parsed_meta = raw_meta
            else:
                parsed_meta = raw_meta
            data['metadata_'] = parsed_meta

            # Extract AI generation flags from metadata for the dedicated fields
            if isinstance(parsed_meta, dict):
                data['ai_generated'] = parsed_meta.get('ai_generated', data.get('role') == 'assistant')
                data['generation_metadata'] = parsed_meta.get('generation_metadata')

            return super().model_validate(data, **kwargs)
        return super().model_validate(obj, **kwargs)


class ConversationResponse(BaseModel):
    """Summary of a conversation."""
    model_config = ConfigDict(from_attributes=True)

    id: str
    user_id: str
    title: str
    agent_type: str
    summary: str | None = None
    created_at: datetime
    updated_at: datetime


class ConversationDetailResponse(ConversationResponse):
    """Conversation with full message history."""
    messages: list[MessageResponse] = []


class ConversationListResponse(BaseModel):
    """Paginated list of conversations."""
    conversations: list[ConversationResponse]
    total: int
    page: int = 1
    page_size: int = 20


class TTSRequest(BaseModel):
    """Request body for text-to-speech conversion."""
    text: str = Field(
        ..., min_length=1, max_length=5000,
        description="Text to convert to speech (max 5000 characters)",
    )
    voice: str | None = Field(
        default=None,
        description="Voice name override (e.g. zh-CN-XiaoxiaoNeural). Ignored if preset is set.",
    )
    preset: str | None = Field(
        default="warm_female",
        description="Voice preset: formal_female, formal_male, warm_female",
    )
    rate: str = Field(
        default="+0%",
        description="Speech rate adjustment (e.g. '+20%', '-10%')",
    )
    volume: str = Field(
        default="+0%",
        description="Volume adjustment (e.g. '+50%')",
    )
    pitch: str = Field(
        default="+0Hz",
        description="Pitch offset (e.g. '+5Hz', '-10%')",
    )
    use_ssml: bool = Field(
        default=False,
        description="Enable SSML for better prosody (adds sentence breaks, style control)",
    )
    style: str | None = Field(
        default=None,
        description="Speaking style for Neural voices (e.g. 'chat', 'serious', 'friendly')",
    )
    response_format: str = Field(
        default="mp3",
        description="Audio format: mp3 (default)",
    )
