"""Contract review schemas."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class RiskItem(BaseModel):
    """A single risk identified in a contract."""
    risk_level: str = Field(..., description="high, medium, or low")
    category: str = Field(..., description="Risk category (e.g., liability, termination, IP)")
    clause: str = Field(..., description="Relevant clause text")
    description: str = Field(..., description="Explanation of the risk")
    suggestion: str = Field(..., description="Suggested revision or mitigation")


class ContractReviewRequest(BaseModel):
    """Request to review a contract."""
    document_id: str | None = Field(
        default=None, description="ID of a previously uploaded document"
    )
    review_type: str = Field(
        default="comprehensive",
        description="Review type: comprehensive, quick, risk_only, compliance",
    )


class ContractReviewResponse(BaseModel):
    """Result of a contract review."""
    model_config = ConfigDict(from_attributes=True)

    id: str
    document_id: str | None = None
    status: str
    overall_score: int | None = Field(default=None, ge=0, le=100, description="0-100 risk score")
    summary: str | None = None
    risks: list[RiskItem] = []
    created_at: datetime
    ai_generated: bool = Field(
        default=True,
        description="Whether the analysis was generated by AI (per 人工智能生成合成内容标识办法)",
    )
    watermark_info: dict[str, Any] | None = Field(
        default=None,
        description="AI content watermark metadata",
    )
    generation_metadata: dict[str, Any] | None = Field(
        default=None,
        description="Content generation metadata including model and timestamp",
    )


class ContractReviewListResponse(BaseModel):
    """Paginated list of contract reviews."""
    reviews: list[ContractReviewResponse]
    total: int
    page: int = 1
    page_size: int = 20
