"""Document generation schemas."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class DocumentGenRequest(BaseModel):
    """Request to generate a legal document."""
    template_type: str = Field(
        ..., description="Document type: complaint_filing, defense_statement, legal_opinion, lawyer_letter, arbitration_request"
    )
    parameters: dict[str, str] = Field(
        default_factory=dict,
        description="Key-value pairs for template placeholders",
    )
    language: str = Field(default="zh", description="Output language: zh or en")


class DocumentTemplateResponse(BaseModel):
    """Available document template."""
    template_type: str
    name: str
    description: str
    category: str
    required_fields: list[str] = []


class DocumentGenResponse(BaseModel):
    """Generated legal document response."""
    model_config = ConfigDict(from_attributes=True)

    id: str
    template_type: str
    title: str
    content: str
    language: str
    created_at: datetime
    ai_generated: bool = Field(
        default=True,
        description="Whether the content was generated by AI (per 人工智能生成合成内容标识办法)",
    )
    watermark_info: dict[str, Any] | None = Field(
        default=None,
        description="AI content watermark metadata (model, timestamp, user_hash)",
    )
    generation_metadata: dict[str, Any] | None = Field(
        default=None,
        description="Content generation metadata including model, timestamp, and provenance",
    )


class DocumentTemplateListResponse(BaseModel):
    """List of available document templates."""
    templates: list[DocumentTemplateResponse]
    total: int
